name: Arduino Compile

on:
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Arduino AVR core
        run: arduino-cli core install arduino:avr

      - name: Install libraries
        run: make install

      - name: Compile sketch
        run: make compile

      - name: Install Clang
        run: |
          sudo apt update
          sudo apt install clang-format-21

      - name: clang-format check
        run: make format-check
